/*
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateUserDto;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appControllerGetHelloTest() throws ApiException {
        String response = api.appControllerGetHello();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userControllerCreateTest() throws ApiException {
        CreateUserDto createUserDto = null;
        User response = api.userControllerCreate(createUserDto);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userControllerFindAllTest() throws ApiException {
        List<User> response = api.userControllerFindAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userControllerFindOneTest() throws ApiException {
        String id = null;
        User response = api.userControllerFindOne(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userControllerRemoveTest() throws ApiException {
        String id = null;
        String response = api.userControllerRemove(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userControllerUpdateTest() throws ApiException {
        String id = null;
        Object body = null;
        String response = api.userControllerUpdate(id, body);
        // TODO: test validations
    }

}
